# Generated by Django 3.2.15 on 2024-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
