# Generated by Django 3.2.15 on 2024-01-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20240118_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_field',
            field=models.ImageField(default='images/default-blog-thumb.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
